import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Head} from "next/document";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Remindr',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="google-site-verification" content="gY8XbUrGrstYF6_GWFfTO2DeA2gTL4SoKnc-njBM3KY" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
